### ISSUE TITLE
Problèmes de droits lors de l'installation déportée

### ISSUE THREAD

**Issue by BadWolf42** [lunarok/jeedom_playtts#5]
Dans le script resources/install.sh, ligne 29, l'utilisateur `www-data` est utilisé au lieu de l'utilisateur fourni :
`sudo usermod -a -G audio www-data`
un correctif éléguant est le suivant :
`sudo usermod -a -G audio ``whoami`` ` (avec une seule apostrophe)

**Comment by lunarok** [comment]
si tu sais quelle commande il faut, c'était plus simple de faire un PR directement
En tout cas ->[ FAIT](https://github.com/lunarok/jeedom_playtts/commit/3a46d760c140f0fc07486fac953b642df6f88adc)

**Comment by BadWolf42** [comment]
Ok merci, c'est noté pour les PR pour la prochaines fois...
